### ISSUE TITLE
Outdated uiuc.edu links

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#3585]
These are almost all dead links:
```
M2/Macaulay2$ grep -iR "uiuc.edu/mac" -l
m2/packages.m2
packages/Points.m2
packages/Schubert2.m2
packages/NumericalSchubertCalculus/README
packages/Macaulay2Doc.m2
packages/RandomCurvesOverVerySmallFiniteFields.m2
packages/Style/icon.gif
packages/BGG.m2
packages/RandomSpaceCurves.m2
packages/Macaulay2Doc/changes.m2
packages/Macaulay2Doc/overview3.m2
packages/Macaulay2Doc/ov_getting_started.m2
packages/Cremona/documentation.m2
packages/Benchmark.m2
packages/Polyhedra/tests/fails_from_googlegroup.txt
packages/WeylGroups/tutorial.html
man/M2.1.in
```
ps: curious that the `icon.gif` has a link in it!!

**Comment by d-torrance** [comment]
Fixed in #3586

**Comment by mahrud** [comment]
I think you missed `distributions/deb/README`, though maybe that one is going to be deleted at some point? It's not urgent enough for me to renew.

**Comment by d-torrance** [comment]
> I think you missed `distributions/deb/README`, though maybe that one is going to be deleted at some point? It's not urgent enough for me to renew.

Yeah -- that link doesn't exist on the webpage any more as far as I could tell, so I didn't bother with it.  The README could definitely use an overhaul/deletion at some point soon.  I'm not sure if anyone uses the autotools build to build Debian packages any more, anyway.

**Comment by mahrud** [comment]
Wait, don't you use it? (I know you have various patches, but I thought the build process itself was the same)

**Comment by d-torrance** [comment]
No -- the Debian packaging code is all in the `debian` directory at https://salsa.debian.org/math-team/macaulay2.  Debian (and Ubuntu PPA's) require a source package, but the autotools build generates a binary package.
